import fs from 'fs';
import path from 'path';
import puppeteer from 'puppeteer';

const schoolHeading = process.env.PAPER_SCHOOL_HEADING || 'Delhi Public School, Sector-4, Bokaro';

const escapeHtml = (value: unknown) =>
  String(value ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');

const normalizeSectionTitle = (title: string) => {
  if (title.includes(':')) {
    return title.split(':')[1].trim();
  }

  return title;
};

const getDifficultyLabel = (difficulty?: string) => {
  if (difficulty === 'easy') return 'Easy';
  if (difficulty === 'hard') return 'Challenging';
  return 'Moderate';
};

const buildHtmlTemplate = (result: any, assignment: any, isAnswerKey: boolean) => {
  const subject = escapeHtml(assignment?.subject || 'English');
  const className = escapeHtml(assignment?.className || '5th');
  const totalMarks = Number(assignment?.questionConfig?.totalMarks || 20);
  const duration = Number(assignment?.questionConfig?.duration || 45);

  const sectionsHtml = (result?.sections || [])
    .map((section: any, sectionIndex: number) => {
      const sectionTitle = escapeHtml(normalizeSectionTitle(section?.title || `Section ${sectionIndex + 1}`));
      const sectionInstruction = escapeHtml(section?.instruction || 'Attempt all questions. Each question carries 2 marks');

      const questionsHtml = (section?.questions || [])
        .map((question: any, questionIndex: number) => {
          const marks = Number(question?.marks || 2);
          const questionText = escapeHtml(question?.text || '');
          const answerHint = escapeHtml(question?.answerHint || 'Answer guidance generated by VedaAI.');

          return `
            <li>
              <span class="muted">[${getDifficultyLabel(question?.difficulty)}]</span>
              ${questionText}
              <span class="muted"> [${marks} Marks]</span>
              ${isAnswerKey ? `<div class="answer-inline"><strong>Hint:</strong> ${answerHint}</div>` : ''}
            </li>
          `;
        })
        .join('');

      return `
        <section class="paper-section">
          <h3 class="section-alpha">Section ${String.fromCharCode(65 + sectionIndex)}</h3>
          <p class="section-title">${sectionTitle}</p>
          <p class="section-instruction">${sectionInstruction}</p>
          <ol class="question-list">${questionsHtml}</ol>
        </section>
      `;
    })
    .join('');

  const answerKeyHtml = (result?.sections || [])
    .flatMap((section: any) => section?.questions || [])
    .map((question: any) => `<li>${escapeHtml(question?.answerHint || 'Answer guidance generated by VedaAI.')}</li>`)
    .join('');

  const answerKeySectionHtml = isAnswerKey
    ? `
      <section class="answer-key">
        <h4>Answer Key:</h4>
        <ol>${answerKeyHtml}</ol>
      </section>
    `
    : '';

  return `
  <!DOCTYPE html>
  <html lang="en">
    <head>
      <meta charset="UTF-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <title>${subject} Assessment</title>
      <style>
        @page { margin: 10mm; }
        * { box-sizing: border-box; }
        body {
          margin: 0;
          font-family: Inter, Arial, Helvetica, sans-serif;
          color: #24272f;
          background: #ffffff;
        }
        .paper-card {
          background: #f4f5f7;
          border: 1px solid #e6e8ed;
          border-radius: 30px;
          padding: 24px;
        }
        .paper-heading {
          text-align: center;
          margin-bottom: 8px;
        }
        .paper-heading h1 {
          margin: 0;
          font-size: 24px;
          line-height: 1.2;
          font-weight: 700;
          color: #24272f;
        }
        .paper-heading p {
          margin: 3px 0;
          font-size: 18px;
          line-height: 1.25;
          font-weight: 700;
          color: #2f3138;
        }
        .meta-row {
          margin-top: 14px;
          display: flex;
          justify-content: space-between;
          gap: 10px;
          font-size: 14px;
          font-weight: 700;
          color: #2e3138;
        }
        .note {
          margin-top: 16px;
          margin-bottom: 8px;
          font-size: 14px;
          font-weight: 500;
          color: #2d3037;
        }
        .student-lines {
          margin-bottom: 16px;
          font-size: 13px;
          line-height: 1.55;
          font-weight: 600;
          color: #2d3037;
        }
        .line {
          display: inline-block;
          width: 140px;
          margin-left: 6px;
          border-bottom: 2px solid #787c85;
          transform: translateY(-2px);
        }
        .paper-section {
          margin-top: 10px;
        }
        .section-alpha {
          margin: 0 0 14px;
          text-align: center;
          font-size: 56px;
          line-height: 1.05;
          font-weight: 700;
          color: #24272f;
        }
        .section-title {
          margin: 0;
          font-size: 18px;
          line-height: 1.2;
          font-weight: 700;
          color: #2c2f36;
        }
        .section-instruction {
          margin: 2px 0 8px;
          font-size: 15px;
          line-height: 1.35;
          font-style: italic;
          color: #5f636d;
        }
        .question-list {
          margin: 0;
          padding-left: 22px;
          font-size: 14px;
          line-height: 1.6;
          color: #2b2e35;
        }
        .question-list li {
          margin-bottom: 6px;
          page-break-inside: avoid;
        }
        .muted {
          color: #4a4e57;
        }
        .answer-inline {
          margin: 4px 0 0;
          font-size: 13px;
          color: #40444c;
        }
        .paper-end {
          margin-top: 10px;
          font-size: 14px;
          font-weight: 700;
          color: #2a2d34;
        }
        .answer-key {
          margin-top: 12px;
          padding-top: 8px;
          border-top: 1px solid #dfe2e8;
        }
        .answer-key h4 {
          margin: 0 0 8px;
          font-size: 18px;
          font-weight: 700;
          color: #2a2d34;
        }
        .answer-key ol {
          margin: 0;
          padding-left: 22px;
          font-size: 13px;
          line-height: 1.55;
          color: #2b2e35;
        }
        .answer-key li {
          margin-bottom: 4px;
          page-break-inside: avoid;
        }
      </style>
    </head>
    <body>
      <article class="paper-card">
        <header class="paper-heading">
          <h1>${escapeHtml(schoolHeading)}</h1>
          <p>Subject: ${subject}</p>
          <p>Class: ${className}</p>
        </header>

        <section class="meta-row">
          <span>Time Allowed: ${duration} minutes</span>
          <span>Maximum Marks: ${totalMarks}</span>
        </section>

        <p class="note">All questions are compulsory unless stated otherwise.</p>
        <div class="student-lines">
          <div>Name: <span class="line"></span></div>
          <div>Roll Number: <span class="line"></span></div>
          <div>Class: ${className} Section: <span class="line" style="width: 90px"></span></div>
        </div>

        ${sectionsHtml}

        <p class="paper-end">End of Question Paper</p>

        ${answerKeySectionHtml}
      </article>
    </body>
  </html>
`;
};

export const generatePDF = async (result: any, assignment: any, isAnswerKey = false): Promise<string> => {
  const browser = await puppeteer.launch({
    headless: true,
    args: ['--no-sandbox', '--disable-setuid-sandbox'],
  });
  const page = await browser.newPage();

  const htmlContent = buildHtmlTemplate(result, assignment, isAnswerKey);
  await page.setContent(htmlContent, { waitUntil: 'networkidle0' });

  const publicDir = path.join(__dirname, '../../public/pdfs');
  if (!fs.existsSync(publicDir)) {
    fs.mkdirSync(publicDir, { recursive: true });
  }

  const filename = `assessment-${result._id}${isAnswerKey ? '-key' : ''}.pdf`;
  const filePath = path.join(publicDir, filename);

  await page.pdf({
    path: filePath,
    format: 'A4',
    printBackground: true,
    preferCSSPageSize: true,
  });

  await browser.close();

  return `/pdfs/${filename}`;
};

export default generatePDF;
